source 1_bibliography.sql
source 2_blockedips.sql
source 3_book.sql
source 4_book_peer.sql
source 5_category.sql
source 6_category_assoc.sql
source 7_chronevent.sql
source 8_chronology.sql
source 9_editlogs.sql
source 10_editlogsviewed.sql
source 11_editnotes.sql
source 12_footnotes.sql
source 13_ipcrossref.sql
source 14_kjv.sql
source 15_logexcludeips.sql
source 16_myrevdata.sql
source 18_outline.sql
source 19_peernotes.sql
source 20_playlist.sql
source 21_resource.sql
source 22_resourceassign.sql
source 23_revblog.sql
source 24_settings.sql
source 25_sopssave.sql
source 26_topic.sql
source 27_topic_assoc.sql
source 29_verse.sql
source 30_viewlogs.sql
source 31_wscats.sql
